# Numpy

for working with arrays, matrices, statistical functions and vectorized operations

In [1]:
import numpy as np

### 1. Arrays

In [ ]:
# Basics...

arr1 = np.array([1,2,3,4,5])                    # Tuples, Sets are also supported...

print("Array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape)
print("Reshape:", arr1.reshape(1, 5))
print("New Reshape:\n", arr1.reshape(5, 1))
print("Dimensions:", arr1.ndim)
print("Size (no. of elements):", arr1.size)     # or can use len(arr1)
print("Data tyoe:", arr1.dtype)

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Reshape: [[1 2 3 4 5]]
New Reshape:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Dimensions: 1
Size (no. of elements): 5
Data tyoe: int64


In [16]:
use_tuple = np.array((1,2,3,4,5))
print("Tuple: ", use_tuple)
print("Size:", use_tuple.size, "| Type:", type(use_tuple), "\n")

use_set = np.array({1,2,1,3,4,1,5,2})
print("Set: ", use_set)
print("Size:", use_set.size, "| Type:", type(use_set), "\n")

use_dict = np.array({1: 1, 2: 2, 3: 3, 4: 4, 5: 5})
print("Dictionary: ", use_dict)
print("Size:", use_dict.size, "| Type:", type(use_dict), "\n")

Tuple:  [1 2 3 4 5]
Size: 5 | Type: <class 'numpy.ndarray'> 

Set:  {1, 2, 3, 4, 5}
Size: 1 | Type: <class 'numpy.ndarray'> 

Dictionary:  {1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
Size: 1 | Type: <class 'numpy.ndarray'> 



### # Common Errors

In [ ]:
# Errors...

arr1 = np.array([1,2,3,4,5,6,7])

arr1.reshape(1, 5)                  # ERROR - as no. of elements are 7, so will not fit.
np.ones(3, 5)                       # Invalid syntax, it should be np.ones((3, 5)).
arr1 + np.array([1, 2, 3, 4])       # operands could not be broadcast together with shapes (7,) (4,)

### 2. Matrices and Methods

In [6]:
# Matrices and Default methods to create array...

print("Using 'arange' func:", np.arange(0, 5))
print("\n", np.arange(0, 6, 2).reshape(3, 1))
print("\nOnes:\n", np.ones((3, 5)))             # Careful with syntax
print("\nZeroes:\n", np.zeros((3,5)))
print("\nIdentity Matrix:\n", np.eye(3, 4))

Using 'arange' func: [0 1 2 3 4]

 [[0]
 [2]
 [4]]

Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Zeroes:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 3. Vectorized Operations

In [ ]:
# Vectorized operations...
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([12, 13, 45, 23, 45])

print("Addition:", arr1 + arr2)
print("Substraction:", arr2 - arr1)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

print("Multiplication with Scalar: ", 2 * arr1)
print("Addition with Scalar: ", 2 + arr1)

Addition: [13 15 48 27 50]
Substraction: [11 11 42 19 40]
Multiplication: [ 12  26 135  92 225]
Division: [12.    6.5  15.    5.75  9.  ]
Multiplication with Scalar:  [ 2  4  6  8 10]
Addition with Scalar:  [3 4 5 6 7]


### 4. Miscelleneous

In [ ]:
# Universal functions...

print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))
print("Sin function:", np.sin(arr1))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sin function: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [21]:
# Array slicing and indexing

arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print('Array:\n', arr3, '\n')
print("Single element:", arr3[0][0], '\n') # or use arr3[0,0]
print("Rows (1 -> 3):\n", arr3[1:], '\n') 
print("Row 0th:", arr3[0], '\n')
print("5 6 8 9 :\n", arr3[1:, 1:]) # using arr3[1:][1:] will give [7,8,9]
arr3[0][0] = 777
arr3[1:] = 777
print("\n Array:\n", arr3)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Single element: 1 

Rows (1 -> 3):
 [[4 5 6]
 [7 8 9]] 

Row 0th: [1 2 3] 

5 6 8 9 :
 [[5 6]
 [8 9]]

 Array:
 [[777   2   3]
 [777 777 777]
 [777 777 777]]


In [73]:
# Statistical Concepts

print("mean:", np.mean(arr1))
print("median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))
print('Variance:', np.var(arr1))


mean: 3.0
median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [81]:
# special operations...

data = np.arange(0, 10)

print(data > 5)
print(data[data > 5])
print(data[(data > 5) & (data < 8)])

[False False False False False False  True  True  True  True]
[6 7 8 9]
[6 7]
